### ISSUE TITLE
Newest version seem to use much more RAM

### ISSUE THREAD

**Issue by TheRealDadbeard** [timrwood/roost#61]
So I updated to 2.0.7 and minecraft uses like 1gb more ram and multiple enderio chickens have their texture broken.

**Comment by codewarrior0** [comment]
EnderIO chickens fixed. Will look into the ram usage.

**Comment by TheRealDadbeard** [comment]
Yep those are good now but ram usage starting mc is way higher. Multiple times hitting red on 4gb on 2.x and never on 1.3

**Comment by kellixon** [comment]
Because of version 2.0.9, the resourcepack is loaded twice ("Reloading textures"). On the 3rd stage of loading Forge and on the 6th. Version 1.3.0 works fine.
Load time 155 mods (+ Roost 2.0.9)=284 sec. - https://gist.github.com/kellixon/fdb62053adfe8c109c463bb0a1ae71a6
Load time 155 mods (+ Roost 1.3.0)=211 sec. - https://gist.github.com/kellixon/7fc5e25c11df9f7e90bcb07cadb9db0f

**Comment by GhEppIO82** [comment]
i have some issue starting minecraft with new update take 15 minute to start without update 6 minute 
this is a very problem for me

**Comment by codewarrior0** [comment]
Changed to only reload resources a second time if absolutely required. Also changed it not to create models until they are actually used in game, which should improve load time and RAM usage even more.

**Comment by GhEppIO82** [comment]
so from what I understand, only the first time the pack takes so long to load ??, it doesn't seem to me ..... but I don't know if I understand what you mean

**Comment by codewarrior0** [comment]
Should be fixed in 2.0.10
